apiVersion: archon.kubeup.com/v1
kind: InstanceGroup
metadata:
  name: k8s-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-master
  template:
    metadata:
      labels:
        app: k8s-master
      annotations:
        initializers: archon.kubeup.com/public-ip
    spec:
      secrets:
      - name: password
      networkName: k8s-net
      instanceType: Normal
      os: Ubuntu
      image: uimage-h2aq0m
      files:
      - name: apt-pgp 
        path: "/tmp/kubernetes.pgp"
        content: |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          
          mQENBFUd6rIBCAD6mhKRHDn3UrCeLDp7U5IE7AhhrOCPpqGF7mfTemZYHf/5Jdjx
          cOxoSFlK7zwmFr3lVqJ+tJ9L1wd1K6P7RrtaNwCiZyeNPf/Y86AJ5NJwBe0VD0xH
          TXzPNTqRSByVYtdN94NoltXUYFAAPZYQls0x0nUD1hLMlOlC2HdTPrD1PMCnYq/N
          uL/Vk8sWrcUt4DIS+0RDQ8tKKe5PSV0+PnmaJvdF5CKawhh0qGTklS2MXTyKFoqj
          XgYDfY2EodI9ogT/LGr9Lm/+u4OFPvmN9VN6UG+s0DgJjWvpbmuHL/ZIRwMEn/tp
          uneaLTO7h1dCrXC849PiJ8wSkGzBnuJQUbXnABEBAAG0QEdvb2dsZSBDbG91ZCBQ
          YWNrYWdlcyBBdXRvbWF0aWMgU2lnbmluZyBLZXkgPGdjLXRlYW1AZ29vZ2xlLmNv
          bT6JAT4EEwECACgFAlUd6rICGy8FCQWjmoAGCwkIBwMCBhUIAgkKCwQWAgMBAh4B
          AheAAAoJEDdGwginMXsPcLcIAKi2yNhJMbu4zWQ2tM/rJFovazcY28MF2rDWGOnc
          9giHXOH0/BoMBcd8rw0lgjmOosBdM2JT0HWZIxC/Gdt7NSRA0WOlJe04u82/o3OH
          WDgTdm9MS42noSP0mvNzNALBbQnlZHU0kvt3sV1YsnrxljoIuvxKWLLwren/GVsh
          FLPwONjw3f9Fan6GWxJyn/dkX3OSUGaduzcygw51vksBQiUZLCD2Tlxyr9NvkZYT
          qiaWW78L6regvATsLc9L/dQUiSMQZIK6NglmHE+cuSaoK0H4ruNKeTiQUw/EGFaL
          ecay6Qy/s3Hk7K0QLd+gl0hZ1w1VzIeXLo2BRlqnjOYFX4A=
          =HVTm
          -----END PGP PUBLIC KEY BLOCK-----
      - name: apt
        path: "/config/apt"
        content: |
          primary:
            - arches: [default]
              uri: http://mirrors.ucloud.cn/ubuntu
      - name: apt-source
        path: "/etc/apt/sources.list.d/kubernetes.list"
        content: |
          deb https://mirrors.ustc.edu.cn/kubernetes/apt/ kubernetes-xenial main
      - name: docker-mirror
        path: "/etc/docker/daemon.json"
        template: |
          {
            "registry-mirrors": ["{{ index .Configs "k8s" "docker-mirror" }}"]
          }
      - name: run-kubeadm
        path: "/tmp/run-kubeadm"
        permissions: "0755"
        template: |
          #! /bin/bash
          #
          set -e
          cloud-init-per once aptaddsource apt-key add /tmp/kubernetes.pgp
          cloud-init-per once aptinstall /bin/sh -c "apt update && apt install -y docker.io kubeadm={{ index .Configs "k8s" "components-version" }} kubelet kubectl kubernetes-cni"

          KUBE_HYPERKUBE_IMAGE={{ index .Configs "k8s" "hyperkube-img" }} KUBE_ETCD_IMAGE={{ index .Configs "k8s" "etcd-img" }} KUBE_REPO_PREFIX={{ index .Configs "k8s" "repo-prefix" }} kubeadm init --config /tmp/kubeadm.conf 
          
          kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://github.com/coreos/flannel/raw/v0.8.0/Documentation/kube-flannel-rbac.yml
          wget -O /tmp/flannel.yml https://github.com/coreos/flannel/raw/v0.8.0/Documentation/kube-flannel.yml
          sed -i "s,quay\.io/coreos,registry.aliyuncs.com/archon,g" /tmp/flannel.yml
          kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /tmp/flannel.yml
      - name: kubeadm-config
        path: "/tmp/kubeadm.conf"
        template: |
          apiVersion: kubeadm.k8s.io/v1alpha1
          kind: MasterConfiguration
          networking:
            podSubnet: {{ index .Configs "k8s" "pod-ip-range" }}
          kubernetesVersion: {{ index .Configs "k8s" "k8s-version" }}
          token: {{ index .Configs "k8s" "token" }}
          authorizationMode: AlwaysAllow
          skipPreflightChecks: true
      - name: kubeadm
        path: "/config/runcmd/kubeadm"
        template: |-
          - /tmp/run-kubeadm |tee /var/log/kubeadm.log
      - name: kubelet-dropin
        path: "/etc/systemd/system/kubelet.service.d/99-archon-dropin.conf"
        template: |
          [Service]
          Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni"
          Environment="KUBELET_EXTRA_ARGS=--pod-infra-container-image={{ index .Configs "k8s" "pause-img"}}"
      users:
      - name: myuser
      configs:
      - name: k8s
        data:
          docker-mirror: https://docker.mirrors.ustc.edu.cn
          pause-img: registry.aliyuncs.com/archon/pause-amd64:3.0
          hyperkube-img: registry.aliyuncs.com/archon/hyperkube-amd64:v1.6.1
          k8s-version: v1.6.1
          components-version: 1.7.0-00
          etcd-img: registry.aliyuncs.com/archon/etcd:3.0.17
          repo-prefix: registry.aliyuncs.com/archon
          pod-ip-range: 10.244.0.0/16
          token: YOUR_KUBEADM_TOKEN
