// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by defaulter-gen. Do not edit it manually!

package cluster

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Instance{}, func(obj interface{}) { SetObjectDefaults_Instance(obj.(*Instance)) })
	scheme.AddTypeDefaultingFunc(&InstanceGroup{}, func(obj interface{}) { SetObjectDefaults_InstanceGroup(obj.(*InstanceGroup)) })
	scheme.AddTypeDefaultingFunc(&InstanceGroupList{}, func(obj interface{}) { SetObjectDefaults_InstanceGroupList(obj.(*InstanceGroupList)) })
	scheme.AddTypeDefaultingFunc(&InstanceList{}, func(obj interface{}) { SetObjectDefaults_InstanceList(obj.(*InstanceList)) })
	scheme.AddTypeDefaultingFunc(&Network{}, func(obj interface{}) { SetObjectDefaults_Network(obj.(*Network)) })
	scheme.AddTypeDefaultingFunc(&NetworkList{}, func(obj interface{}) { SetObjectDefaults_NetworkList(obj.(*NetworkList)) })
	scheme.AddTypeDefaultingFunc(&ReservedInstance{}, func(obj interface{}) { SetObjectDefaults_ReservedInstance(obj.(*ReservedInstance)) })
	scheme.AddTypeDefaultingFunc(&ReservedInstanceList{}, func(obj interface{}) { SetObjectDefaults_ReservedInstanceList(obj.(*ReservedInstanceList)) })
	return nil
}

func SetObjectDefaults_Instance(in *Instance) {
	SetDefaults_Instance(in)
	SetObjectDefaults_Network(&in.Dependency.Network)
	SetObjectDefaults_ReservedInstance(&in.Dependency.ReservedInstance)
}

func SetObjectDefaults_InstanceGroup(in *InstanceGroup) {
	SetDefaults_InstanceGroup(in)
}

func SetObjectDefaults_InstanceGroupList(in *InstanceGroupList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_InstanceGroup(a)
	}
}

func SetObjectDefaults_InstanceList(in *InstanceList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Instance(a)
	}
}

func SetObjectDefaults_Network(in *Network) {
	SetDefaults_Network(in)
}

func SetObjectDefaults_NetworkList(in *NetworkList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Network(a)
	}
}

func SetObjectDefaults_ReservedInstance(in *ReservedInstance) {
	SetDefaults_ReservedInstance(in)
}

func SetObjectDefaults_ReservedInstanceList(in *ReservedInstanceList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ReservedInstance(a)
	}
}
